### ISSUE TITLE
apm --version crashes with Error: spawn UNKNOWN

### ISSUE THREAD

**Issue by wolfy1339** [atom/apm#822] opened 2018-10-25 19:30 UTC
### Prerequisites
None of these are applicable for this issue. This is an issue with apm itself and not it's integration into Atom.
* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. Add Atom install to path
2. Run `apm --version`

**Expected behavior:** Return the version information
**Actual behavior:** It doesn't return the version information, it instead errors
```
$ apm --version
internal/child_process.js:323
    throw errnoException(err, 'spawn');
    ^

Error: spawn UNKNOWN
    at _errnoException (util.js:1024:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:502:9)
    at EventEmitter.<anonymous> (C:\Users\<user>\AppData\Local\atom\app-1.34.0-nightly3\resources\app\apm\lib\apm-cli.js:169:17)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Reproduces how often:** 100%
### Versions
```
$ $USERPROFILE\\AppData\\Local\\atom\\\app-1.34.0-nightly3\\resources\\app\\apm\\bin\\apm --version
```
```
$ atom --version

Atom    : 1.34.0-nightly3
Electron: 2.0.11
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

### Additional Information

This is running on Widows 10 Pro 1803 64 bit.

**Comment by rsese** [comment] 2018-10-30 06:10
> * Add Atom install to path

**Comment by rsese** [comment] 2018-10-30 06:16
Sorry accidentally commented, edited by comment above.

Another question as well, do all the apm commands error the same way?  E.g. what about `apm list` for example?

Lastly, are you running these command from PowerShell, cmd, or some other program?

**Comment by wolfy1339** [comment] 2018-10-30 10:57
Yes, I am running that from the command line.
 I added `%APPDATA\atom\bin` (Maybe a little different, but it's the path in the AppData that contains the install.
Sure thing, I will update atom once I get the chance.
apm was broken for a couple versions now even on the stable build

**Comment by wolfy1339** [comment] 2018-11-01 19:08
Here is some more information as requested:
- No difference with updated atom
- `apm list` works fine
- I'm running them from Git Bash
- If I call the apm in the versioned folder, It works fine

**Comment by rsese** [comment] 2018-11-07 01:30
> * I'm running them from Git Bash

Ahh ok - just to confirm, do you see this error in cmd.exe or PowerShell?

**Comment by wolfy1339** [comment] 2018-11-07 01:31
cmd works fine

**Comment by rsese** [comment] 2018-11-08 22:34
Thanks @wolfy1339 - I reproduced with Git for Windows 2.19.1 on Windows 10 as well.  I remember an older issue though and looking at it, I'm going to tentatively close this as a duplicate of https://github.com/atom/apm/issues/725 and you can subscribe there if you'd like.  Someone mentions Git Bash in the comments but I'll update the issue body as well..

**Closed by rsese** 2018-11-08 22:34 UTC
