### ISSUE TITLE
Package search doesn't work

### ISSUE THREAD

**Issue by tiborsaas** [atom/apm#618] opened 2016-10-16 13:22 UTC
Hello,

Is this normal? :) I'd assume I enter a keyword here and see a list of packages. 

![image](https://cloud.githubusercontent.com/assets/342688/19417718/3a27c350-93b4-11e6-9748-c3f382cce0a9.png)

I'm on Windows 10

**Comment by Ben3eeE** [comment] 2016-10-17 15:38
This is a duplicate of https://github.com/atom/atom/issues/12999.

**Closed by Ben3eeE** 2016-10-17 15:38 UTC
