### ISSUE TITLE
Publishing new patch versions for old major/minor versions

### ISSUE THREAD

**Issue by lexicalunit** [atom/apm#654] opened 2016-12-06 15:52 UTC
# Summary

Currently there are some breaking changes between Atom v1.12 and v1.13 (beta). I released a version that targets v1.13. Then I needed to release a patch version for a previous version of my package, the version that targets v1.12. However it does not seem possible. I thought it would be as simple as manually providing the tag on the command line.

# Reference

This was discussed initially on the Atom forums, https://discuss.atom.io/t/can-not-publish-a-patch-for-an-older-version/36517/4 Below is a copy of my initial post from that page.

I'm trying to publish a patch version of an older version of a package. The latest version is for Atom 1.13 only, but I need to push out a fix for a version that is for Atom 1.12 only.

Here's what I did:

    $ git co v0.25.2
    $ git co -b feature/branch
    # edited code
    $ git add --all
    $ git ci -m "blah blah"
    $ git push -fu origin feature/branch
    # on github, merged the branch into master
    $ apm publish -t 0.25.3
    Publishing multi-wrap-guide@v0.25.3 ✗
    Creating new version failed: Git tag not found

Uh.. OK? So I created the tag myself.

    $ git tag v0.25.3
    $ apm publish -t 0.25.3
    Publishing multi-wrap-guide@v0.25.3 ✗
    Creating new version failed: Git tag not found

O... kay... I guess I need to push the tag to origin first?

    $ git push origin v0.25.3
    $ apm publish -t 0.25.3
    Publishing multi-wrap-guide@v0.25.3 ✗
    Creating new version failed: Version exists

Um no. I literally just created the tag myself. The version does NOT exist yet.

Is there a way to force apm to publish this correctly?

**Comment by lee-dohm** [comment] 2016-12-06 17:48
Thanks for documenting this for us! I've brought it up to the dev team and we're going to see what we can do.

**Comment by daaain** [comment] 2017-02-06 16:37
I think I ran into the same issue and managed to work around it.

Basically it seems that APM creates the tag `vx.x.x` but is looking for `x.x.x`.

Manually telling it to use `vx.x.x` works.

```
$ apm publish patch
Preparing and tagging a new version ✓
Pushing v1.7.1 tag ✓
Publishing Handlebars@v1.7.1 ✗
Creating new version failed: Git tag not found
$ apm publish --tag 1.7.1
Publishing Handlebars@1.7.1 ✗
Creating new version failed: Git tag not found
$ apm publish --tag v1.7.1
Publishing Handlebars@v1.7.1 ✓
```

**Comment by lee-dohm** [comment] 2017-02-06 17:25
@daaain Yes, this is specifically about publishing a version number that is smaller than the latest one published.

**Comment by daaain** [comment] 2017-02-06 17:56
Ah, sorry then, didn't want to hijack!

Should I open a new issue then as it seems the problem is happening when doing a simple `apm publish patch`?

**Comment by lee-dohm** [comment] 2017-02-06 18:00
@daaain The problem that you're describing is something that is transitory and I'm running down with the back end people right now. No new Issue needed :grinning:

**Comment by xufengli** [comment] 2017-02-28 15:38
I have the same issue and it seems that I can not publish the first version I want to. 
There are two issues:
1. git tag -a  0.0.1 seems can not only create a version with a prefix v in front.  A tag v0.0.1 is created.
2. I found this is not what I wanted, so I run apm publish patch and this publish v0.0.2 for me not even v0.0.1
3. I unpublish all versions and delete the tags, then I publish again. A new version v0.0.3 is published.

How can I publish the version number as what I expected with apm?

**Comment by lee-dohm** [comment] 2017-03-01 00:32
@xufengli That isn't the same problem as this.

If you're having problems publishing your package and are looking for support, please check out either:

* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by jasonrudolph** [comment] 2017-04-11 10:01
@lexicalunit: Thanks for the detailed bug report. :zap::bow:

### Findings

I think I've tracked down the root cause of the behavior you're seeing. I believe `apm publish -t <tag>` expects two important things to be true:

1. *The Git tag already exists*.

   As you saw, you had to create the Git tag to resolve the "Git tag not found" error.

2. *The `package.json` file at that tag contains the version number that you want to use when publishing*.

   This expectation :point_up: is the source of the final error that you ran into:

       $ apm publish -t 0.25.3
       Publishing multi-wrap-guide@v0.25.3 ✗
       Creating new version failed: Version exists

   If we look at [`package.json` at the v0.25.3 tag of lexicalunit/multi-wrap-guide](https://github.com/lexicalunit/multi-wrap-guide/blob/v0.25.3/package.json#L4), the version is specified as `0.25.2`:

   ![screenshot](https://cloud.githubusercontent.com/assets/2988/24776491/079385c4-1aef-11e7-9f04-b6c37b0f8b2f.png)

### Currently-available solutions

I think package authors have two ways to overcome this issue today.

#### Option 1

Before creating the Git tag, edit `package.json` to have the desired version, and ensure that the specified version has not already been published. Using the steps from the [issue body](https://github.com/atom/apm/issues/654#issue-193808274), this solution would function like so:

```
$ git co v0.25.2
$ git co -b feature/branch
# edit code
# change version in package.json to "0.25.3" <=================== NEW STEP
$ git add --all
$ git ci -m "blah blah"
$ git push -u origin feature/branch
# on github.com, merge the branch into master
$ git tag v0.25.3
$ git push origin v0.25.3
$ apm publish -t v0.25.3 <== SPECIFY THE TAG NAME. IT SHOULD BE THE VERSION NUMBER PREFIXED WITH "v".
```

#### Option 2 (Recommended)

On the branch that contains the patch, use `apm publish patch` to tag and publish the patch version.

```
$ git co v0.25.2
$ git co -b feature/branch
# edit code
$ git add --all
$ git ci -m "blah blah"
$ git push -u origin feature/branch
$ apm publish patch
```

Essentially, Option 1 is a more manual approach. It's expecting you to update the version in `package.json` and it's expecting you to create and push the Git tag.

Since Option 2 involves fewer steps, and since it uses the `apm publish patch` command that you'd use for patching the _current_ version of your package, I'd recommend using Option 2.

### Minimizing future confusion

As an attempt to reduce confusion for anyone that runs into a similar issue in the future, we've enhanced the error detection and we've updated the error message to provide additional detail. Instead of this:

    $ apm publish -t 0.25.3
    Creating new version failed: Version exists

You'll now see this:

    $ apm publish -t 0.25.3
    Creating new version failed: You specified a tag with the version number '0.25.3', but the version number in package.json is '0.25.2'. The version numbers must agree before you can publish.

I hope that helps.

---

> Is there a way to force apm to publish this correctly?

I think the explanation above answers this question, so I'm going to close this issue. If you still run into problems publishing a patch for an older version of your package, please let us know.

**Closed by jasonrudolph** 2017-04-11 10:01 UTC
Labels: bug

**Comment by lexicalunit** [comment] 2017-04-12 18:18
Thanks for the detail explanation and improved error message! 🎉
