### ISSUE TITLE
Can't install new packages.

### ISSUE THREAD

**Issue by bigifoot** [atom/apm#774] opened 2018-02-15 20:31 UTC
### Prerequisites
* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Hi,
I installed the last version of Atom for windows 7 64bit and i can install any new packages.
yeas i check every method/ post that have the same issue and still can resolve it.
anyone can help please?

![ddd](https://user-images.githubusercontent.com/36519180/36279289-408ab520-129f-11e8-8ad8-65990409c26f.PNG)

apm -v
apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.24.0
python 2.7.14
git 2.16.1.windows.4
visual studio 2015

**Comment by 50Wliu** [comment] 2018-02-17 00:35
This is a duplicate of https://github.com/atom/atom/issues/16760.  Please be sure to read Lee's comment (https://github.com/atom/atom/issues/16760#issuecomment-366344459).

**Closed by 50Wliu** 2018-02-17 00:35 UTC
