### ISSUE TITLE
Atom made portable but not apm

### ISSUE THREAD

**Issue by jackjameshoward** [atom/apm#691] opened 2017-02-28 15:46 UTC
I've manually moving the .atom folder to the atom folder. 
Atom runs perfectly as a portable version, however, apm doesn't. 
Whenever I try to download a package, apm creates a folder in the USER folder. 
I've run apm config list and I can see all default directories point to USER

```
K:\Program Files\Atom\Atom x64\resources\app\apm\bin>apm config list
; cli configs
globalconfig = "C:\Users\jhoward\.atom\.apm\.apmrc"
user-agent = "npm/3.10.5 node/v4.4.5 win32 x64"
userconfig = "C:\Users\jhoward\.atom\.apmrc"

; environment configs
node-gyp = "K:\Program Files\Atom\Atom x64\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js"

; globalconfig C:\Users\jhoward.atom.apm.apmrc
cache = "C:\Users\jhoward\.atom\.apm"
progress = false

; node bin location = K:\Program Files\Atom\Atom x64\resources\app\apm\bin\node.exe
; cwd = K:\Program Files\Atom\Atom x64\resources\app\apm\bin
; HOME = C:\Users\jhoward
; "npm config ls -l" to show all defaults.
```
How do I set the paths to point to the correct directory (which could be any drive letter because it's running portable via USB)?

**Comment by rsese** [comment] 2017-02-28 22:41
After some searching, I noticed that this may be a duplicate of https://github.com/atom/apm/issues/678?  In particular, see the comments starting here for more context and a suggested workaround for the path issue you described:

https://github.com/atom/apm/issues/678#issuecomment-275770107

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-02-28 22:41 UTC
