### ISSUE TITLE
Failed to activate the [package name] package. (No package works)

### ISSUE THREAD

**Issue by benjavides** [atom/apm#443] opened 2015-10-06 15:36 UTC
I was getting errors from every atom package I tried:

rgbkrk/atom-script/#597
AtomLinter/linter-flake8/#82
AtomLinter/linter-pep8/#26

Cause: My windows 8.1 **profile name had a non-Asci character**
Fix (by @oliversalzburg): http://superuser.com/a/499446

**Comment by 50Wliu** [comment] 2015-10-06 15:43
Duplicate of atom/atom#8891, please subscribe there for updates.

**Closed by 50Wliu** 2015-10-06 15:43 UTC

**Comment by oliversalzburg** [comment] 2015-10-06 15:57
Yay, I helped :D

**Comment by joaoportela** [comment] 2015-10-06 16:19
The reports on atom/atom#8891 don't seem to point to the same cause.

**Comment by Arcanemagus** [comment] 2015-10-06 16:43
@joaoportela down at the bottom of the comments there everyone that was having issues reported having non-ascii characters in their path and similar issues to what you and @benjavides so I would guess that this is indeed the same issue.

Worst case we just re-open this after that lands if it is still an issue :wink:.

**Comment by joaoportela** [comment] 2015-10-06 17:26
Skimmed past that too fast. Sorry
