### ISSUE TITLE
Feature Request: Make apm work more like brew and others

### ISSUE THREAD

**Issue by lifeiscontent** [atom/apm#692] opened 2017-03-01 05:37 UTC
### Description

when doing `apm install package-name1 package-name2`

if the package is installed already, apm doesn't do a check to see if it's already installed it just naively reinstalls it unlike brew, yarn and others.

### Steps to Reproduce

1. `apm install atom-ternjs autocomplete-ruby color-picker emmet file-icons git-plus language-babel linter linter-eslint merge-conflicts minimap pigments platformio-ide-terminal project-manager script sort-lines todo-show`
2. repeat step 1
3. see packages reinstall

**Expected behavior:** return a warning and continue with installation of other packages.

**Actual behavior:** reinstalls all packages

**Reproduces how often:** 100%

**Comment by lifeiscontent** [comment] 2017-03-16 15:52
@as-cii any updates here?

**Comment by jyoungs** [comment] 2017-07-27 19:09
Dupe of #170 (which includes a bash workaround)

**Comment by 50Wliu** [comment] 2017-07-27 19:09
Thanks @jyoungs.

**Closed by 50Wliu** 2017-07-27 19:09 UTC
