### ISSUE TITLE
Uninstalling packages is working in a very crude way

### ISSUE THREAD

**Issue by 4rlekin** [atom/apm#390] opened 2015-07-03 08:15 UTC
I stumbled upon this issue today, trying to incorporate save-commands package into my Atom.
Due to certain amount of problems with mentioned package i decided to uninstall it. And well... the "uninstall" button gives no feedback at all about whether it worked or not - it does uninstall though, but then again refreshing of installed packages works unpredictable, usually had to restart atom.
I got some issues with "not-feedbacking" "Enable/Disable" button too.

**Comment by mnquintana** [comment] 2015-07-03 11:50
This is a duplicate of https://github.com/atom/settings-view/issues/529 – please subscribe there for updates.

(Also, this belongs on [atom/settings-view](https://github.com/atom/settings-view), not [atom/apm](https://github.com/atom/settings-view).)

**Closed by mnquintana** 2015-07-03 11:50 UTC
Labels: duplicate, wrong-repo
