### ISSUE TITLE
Engines field not respected when upgrading package

### ISSUE THREAD

**Issue by benogle** [atom/apm#334] opened 2015-04-03 16:29 UTC
Autocomplete has the [engines field](https://github.com/atom-community/autocomplete-plus/blob/f8cac61d045a1ef4440d0bb0351490f9a8f710de/package.json#L8) set to `>=189`, but was allowed to be upgraded on version 188, resulting in https://github.com/atom-community/autocomplete-plus/issues/352

Not sure where the version check is supposed to be done, but assuming `apm`.

**Comment by izuzak** [comment] 2015-04-03 16:37
@benogle  I think this is a duplicate of https://github.com/atom/settings-view/pull/377. apm does check the engines field if you're installing with `apm install`, but settings view doesn't currently.

**Comment by benogle** [comment] 2015-04-03 23:53
Ah noted. Feel free to close. That other pr should be merged at some point

**Comment by mnquintana** [comment] 2015-04-21 12:04
I was able to reproduce this with `apm install` – I just deprecated save-session for >=0.193.0, and a new save-session release was published for this, but `apm install` allowed me to install it anyway. I wonder if this has something to do with using a built version of Atom – ie. it's comparing against `0.193.0-1cc5c83` and not `0.193.0`, which is causing the semver version check to not work properly. Some preliminary testing with semver makes me think this is the case.

**Comment by izuzak** [comment] 2015-04-21 13:43
@mnquintana I'm not sure I'm following. `0.193.0-1cc5c83` is considered a pre-release of `0.193.0`, so it comes _before_ that version ( `0.193.0-1cc5c83` < `0.193.0`). See my comments here: https://github.com/atom/settings-view/issues/359#issuecomment-93292449. As a result, I think the semver check is working as expected and you were allowed to install the package. 

I'm going to close this as a duplicate, but let me know if I'm misunderstanding.

**Comment by mnquintana** [comment] 2015-04-21 20:58
@izuzak That does make sense, but when I ran this (just in Node):

```js
var semver = require('semver');

semver.satisfies('0.193.0-1cc5c83', '<0.193.0')
```

it returned `false`. It should return `true` if it's really being treated as a prerelease to 0.193.0.

**Comment by mnquintana** [comment] 2015-04-22 14:47
This is still an issue - I just tried running `apm install save-session` on Atom 0.194.0, when it has the [following `engines` info](https://github.com/mpeterson2/save-session/blob/master/package.json#L11-L13):

```json
"engines": {
  "atom": ">0.50.0 <0.193.0"
}
```

And apm installed it with no issue.

**Comment by mnquintana** [comment] 2015-04-22 14:53
Update: apm actually installed the last compatible version (0.13.5) instead of trying and failing to install the latest incompatible version (0.14.0)

**Comment by izuzak** [comment] 2015-04-22 14:54
@mnquintana Can't say I'm not surprised by that :smile:. Thanks for digging into this -- I agree with you that there's something strange going on.

First, going back to your [first comment](https://github.com/atom/apm/issues/334#issuecomment-94762296), I just tried installing that package, save-session, and here's what I see:

```
$ apm install save-session
Installing save-session to /Users/izuzak/.atom/packages ✓

$ apm list | grep save-session
├── save-session@0.13.5

$ apm upgrade save-session
Package Updates Available (0)
└── (empty)
```

Version 0.13.5 was installed, not 0.14 (the latest version). Version 0.13.5 has [this engines field](https://github.com/mpeterson2/save-session/blob/v0.13.5/package.json): `"atom": ">0.50.0"`. Version [0.14.0](https://github.com/mpeterson2/save-session/blob/v0.14.0/package.json) has: `"atom": ">0.50.0 <0.193.0"`. My Atom version is `0.193.0-4fb59af`. Given that, it seems that apm did what you expected -- it didn't install the 0.14.0 version. However, it didn't do what I expected -- I expected it would allow me to install 0.14.0 since `0.193.0-4fb59af < 0.193.0`.

Are you seeing the same behavior?

Here's what I'm seeing in console:

```
> semver.satisfies('0.193.0', '>0.193.0-1cc5c83')
true

> semver.satisfies('0.193.0-1cc5c83', '<0.193.0')
false

> semver.compare('0.193.0-1cc5c83', '0.193.0')
-1

> semver.compare('0.193.0', '0.193.0-1cc5c83')
1
```

I expected the `semver.satisfies('0.193.0-1cc5c83', '<0.193.0')` call to return `true` as well, but it seems that's not the case. I think I'll need to read up on https://github.com/npm/node-semver#prerelease-tags to understand why that's so.

Also, taking a closer look at what apm is doing, it seems that it's actually [normalizing](https://github.com/atom/apm/blob/e144f99e01be02322d07f0799bb34b6384c7882f/src/install.coffee#L524) the version, which [removes the prerelease suffix](https://github.com/atom/apm/blob/888594366742885467fe13d01479d4f963758f66/src/command.coffee#L63). So, that `satisfies` call becomes `semver.satisfies('0.193.0', '<0.193.0')` in apm, which returns `false`. Sorry for not double checking that before.

**Comment by izuzak** [comment] 2015-05-04 16:52
Closing in favor of https://github.com/atom/apm/issues/351 which, if I remember correctly, is what @mnquintana really wanted here.

**Closed by izuzak** 2015-05-04 16:52 UTC
Labels: bug
