### ISSUE TITLE
apm is badly named

### ISSUE THREAD

**Issue by gcopeland** [atom/apm#533] opened 2016-03-30 20:30 UTC
On Linux, apm is already used by Advanced Power Management interface, user land tool. Furthermore, this tool is normally placed at /usr/bin/apm.

Proper use for atom to install is to place its binaries in /usr/local or /opt. This will ensure no conflict with system provided tools. So even on systems where apm is not in use, the proper way to install this software should be to install into the /usr/local or /opt trees.

**Comment by 50Wliu** [comment] 2016-03-30 20:40
@gcopeland I'm closing this as a duplicate of atom/atom#3296.  The general consensus appears to be that apmd is extremely outdated and should be uninstalled.

**Closed by 50Wliu** 2016-03-30 20:40 UTC
