### ISSUE TITLE
Failed to install package with CamelCase naming (MagicPython) on MacOS

### ISSUE THREAD

**Issue by manisenkov** [atom/apm#761] opened 2017-12-12 23:26 UTC
### Description

I tried to install `MagicPython` package with command `apm i MagicPython` and it fails with error:
```
$ apm install MagicPython
Installing MagicPython to /Users/maxim/.atom/packages ✓
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/maxim/.atom/packages/MagicPython/package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Proxy.fs.readFileSync (fs.js:508:33)
    at Proxy.fs.readFileSync (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/asar-require/lib/require.js:86:27)
    at /Applications/Atom.app/Contents/Resources/app/apm/lib/install.js:476:42
    at fn (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/async/lib/async.js:582:34)
    at Immediate.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/async/lib/async.js:498:34)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)

$ ([ -d /Users/maxim/.atom/packages/MagicPython ] && echo "package installed") || echo "package not installed"
package not installed
```

However when I tried to do this with the lowercase name of the package it went well:

```
$ apm install magicpython
Installing magicpython to /Users/maxim/.atom/packages ✓
$ ([ -d /Users/maxim/.atom/packages/MagicPython ] && echo "package installed") || echo "package not installed"
package installed
```
(notice that package still installed into "CamelCased" folder, like it should be)

This error also happen in Atom itself:

<img width="686" alt="apm-install-fail" src="https://user-images.githubusercontent.com/6490388/33913846-c8cfcc7c-df9b-11e7-9b11-cd10935c3ea4.png">

### Steps to Reproduce

1. Run shell command `apm install MagicPython`
2. Got exception
3. Check that package is not installed inside `$HOME/.atom/packages`

**Expected behavior:** Package should be installed without any problems.

**Actual behavior:** Package is not installed.

**Reproduces how often:** Everytime when I try to install MagicPython.

### Versions

```
$ atom --version
Atom    : 1.23.0
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

```
$ apm --version
apm  1.18.11
npm  3.10.10
node 6.9.5 x64
atom 1.23.0
python 2.7.14
git 2.15.1
```

```macOS High Sierra 10.13.2```

**Comment by rsese** [comment] 2017-12-13 04:08
Thanks for the report!  I confirmed that `apm install MagicPython` works on 1.22.1 but doesn't on 1.23 so I think this is a duplicate of https://github.com/atom/settings-view/issues/1018 - you can subscribe there for updates if you'd like.

**Closed by rsese** 2017-12-13 04:08 UTC
