### ISSUE TITLE
Cannot Install nuclide in atom

### ISSUE THREAD

**Issue by Zedonboy** [atom/apm#709] opened 2017-04-09 22:22 UTC
### Description

i cannot install nuclide

### Steps to Reproduce
I typed `apm install nuclide` in cmd with admin privelledge

**Expected behavior:** 
for nuclide to be installed

**Actual behavior:** 
gives me this error
```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@4.4.5 | win32 | x64
gyp http GET https://atom.io/download/electron/v1.3.13/iojs-v1.3.13.tar.gz
gyp http 200 https://atom.io/download/electron/v1.3.13/iojs-v1.3.13.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at exports._errnoException (util.js:870:11)
gyp ERR! stack     at TLSWrap.onread (net.js:552:26)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "C:\\Users\\User\\AppData\\Local\\atom\\app-1.15.0\\resources
\\app\\apm\\bin\\node.exe" "C:\\Users\User\\AppData\\Local\\atom\\app-1.15.0\
\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "install" "--run
time=electron" "--target=1.3.13" "--dist-url=https://atom.io/download/electron"
"--arch=x64" "--ensure"
gyp ERR! cwd C:\Users\user\.atom
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
```

**Reproduces how often:** [100%]

### Versions

apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python
git 2.9.3.windows.2
visual studio
windows 8

### Additional Information
Thanks in Advance.

**Comment by thomasjo** [comment] 2017-04-10 08:06
Duplicate of #708

**Closed by thomasjo** 2017-04-10 08:06 UTC

**Comment by Zedonboy** [comment] 2017-04-10 11:51
@thomasjo you have any idea bro?

**Comment by Zedonboy** [comment] 2017-04-10 11:52
ECONRESET problem looks like internet connection.................but am sure my internet connect is good
