### ISSUE TITLE
Cannot run tests with apm-beta without stable installed

### ISSUE THREAD

**Issue by sadovnychyi** [atom/apm#462] opened 2015-10-27 07:18 UTC
I have only atom-beta installed and it's looks like it's hardcoded to use only `atom` thus I'm receiving `Error spawning atom: spawn ENOENT` error.

**Comment by izuzak** [comment] 2015-10-27 10:59
Thanks for the report, @sadovnychyi -- this looks like a duplicate of https://github.com/atom/apm/issues/451. Closing in favor of that, but let me know if I misunderstood your report. :v:

**Closed by izuzak** 2015-10-27 10:59 UTC
