### ISSUE TITLE
apm install reinstalls existing packages

### ISSUE THREAD

**Issue by vrinek** [atom/apm#604] opened 2016-08-21 12:28 UTC
I'm using the following procedure to "sync" a couple of machines:

- `apm list --installed --bare > my-packages.txt`
- `apm install --packages-file my-packages.txt`

Sadly, the second command reinstalls everything, which is slow. I don't see a flag in the documentation that would instruct `apm install` to skip already installed packages.

Am I missing something or is this indeed a bug-report?

**Comment by 50Wliu** [comment] 2016-08-25 16:09
Closing as a duplicate of #170 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-08-25 16:09 UTC

**Comment by vrinek** [comment] 2016-09-01 08:09
Cool, thanks for the heads up!
