### ISSUE TITLE
Use npm3 to mitigate the deep trees and redundancy nesting causes

### ISSUE THREAD

**Issue by KSXGitHub** [atom/apm#556] opened 2016-05-27 03:46 UTC
I found that apm installs all dependencies in a nested way (similar to npm2), which means that each package has its own `node_modules` folder, each package dependency has its own `node_modules` folder, and so on. By this way, installing some packages which depend on same set of dependencies would increases total amount of hard disk used to store these dependencies, it would also occupies amount of RAM used to store some JavaScript objects which have the same structure (i.e. exported objects from one module but placed in different `node_modules` folders of different dependents). This is no good.

npm3 came out resolved this problem. Quoting from [npm documentation](https://docs.npmjs.com/how-npm-works/npm3):

> While npm2 installs all dependencies in a nested way, npm3 tries to mitigate the deep trees and redundancy that such nesting causes. npm3 attempts this by installing some secondary dependencies (dependencies of dependencies) in a flat way, in the same directory as the primary dependency that requires it.

**Steps which explain the enhancement**

1. Run `apm install` from CLI or install a package by using Atom editor
2. apm uses npm3 to install things
3. Every non-duplicated dependencies should be placed at `~/.atom/node_modules` or `~/.atom/packages/node_modules`

**Current and suggested behavior**

 * *Current behaviour:* Similar to npm2, every dependents have their own `node_modules` directory which stores their dependencies.

 * *Suggested behaviour:* Similar to npm3, apm shouldn't download installed dependencies

**Why would the enhancement be useful to most users**

 * Reducing amount of hard drive used to store dependencies
 * Reducing amount of RAM when using Atom
 * Reducing amount of data needed to be downloaded from the Internet
 * Enhancing startup time of Atom
 * Allowing some packages/modules interact which other packages/modules through one intermediate dependency

**Output of `apm version`:**
```
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.11
git 2.8.1.windows.1
visual studio
```

**Atom Version:** 1.7.4
**OS and Version:** Windows 10 Pro 64-bit

**Comment by thomasjo** [comment] 2016-05-27 07:58
Closing as duplicate of https://github.com/atom/apm/issues/436. There's also a (outdated) PR that aims to resolve this. See https://github.com/atom/apm/pull/457.

**Closed by thomasjo** 2016-05-27 07:58 UTC
