### ISSUE TITLE
`apm stars --install` reinstalls already-installed packages

### ISSUE THREAD

**Issue by caleb531** [atom/apm#299] opened 2015-02-15 20:46 UTC
Hi,
I recently discovered Atom and I think it's the greatest thing since sliced bread. I more recently discovered Atom Stars and I think it's pretty neat. I attempted to run `atom stars --install` for myself to see what would happen, assuming that nothing would (because all of my starred packages were already installed).

However, to my surprise, apm attempted to reinstall those packages which already existed in my packages/ directory (all of which were starred and up-to-date). Because I was merely experimenting, this wasn't much of an issue for me, however I can see how this might be an additional inconvenience for others who have only *some* of the starred packages already installed.

Therefore, I am suggesting that `apm stars --install` skip over packages which are already installed. It's a simple request, and I don't know how easy it is to implement, but I do believe that it would be a more intuitive behavior.

**Comment by thedaniel** [comment] 2015-02-16 21:24
Thanks for the feedback! I'm going to close this as I think it's a duplicate of #170.

**Closed by thedaniel** 2015-02-16 21:24 UTC
