### ISSUE TITLE
Run apm failed in Windows subsystem for linux

### ISSUE THREAD

**Issue by mslichao** [atom/apm#850] opened 2019-06-04 05:30 UTC
I installed atom in the windows subsystem for linux, but install packages in atom always failed.

I tried to run `apm` in the bash, it failed too with the error : /usr/bin/apm: line 63: /usr/share/atom/resources/app/apm/bin/`node.exe`: No such file or directory

This is ubuntu, so there is only `node` than `node.exe`, I think this is a bug.

But I found below commit that cause this issue, seems here use `node.exe` is to resolve another issue which I don't know: https://github.com/atom/apm/commit/10525a7bd6b3680d961f7db04e1eb8d7211afb63

So, how to fix the apm issue in WSL?

**Comment by rsese** [comment] 2019-06-05 07:40
Thanks for contributing!

For future issues, please fill out the issue template when opening issues otherwise your issues may be closed.

About your report, not sure if you saw it already but we noticed that it's a duplicate of https://github.com/atom/apm/issues/751 so you can subscribe there for updates if you'd like (though I do want to mention that we don't officially support installing Atom in WSL).

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-06-05 07:40 UTC
