### ISSUE TITLE
Uninstalling Multiple Packages Fails

### ISSUE THREAD

**Issue by epmatsw** [atom/apm#438] opened 2015-09-26 00:35 UTC
I'm trying to uninstall a bunch of packages at once (all of nuclide's packages, specifically). To do this, I've been trying to do `apm list | grep nuclide | xargs apm uninstall`. The output of that:
![screen shot 2015-09-25 at 5 30 47 pm](https://cloud.githubusercontent.com/assets/1126580/10114755/87c1b812-63ab-11e5-816f-30d0241d4a6e.png)
would seem to indicate that it works.

However, if I then `apm list`, I still see all of the packages.
![screen shot 2015-09-25 at 5 30 59 pm](https://cloud.githubusercontent.com/assets/1126580/10114759/9a727ab4-63ab-11e5-8bc2-9f558ddda973.png)

If I `apm uninstall` a single package, it works fine.
![screen shot 2015-09-25 at 5 31 36 pm](https://cloud.githubusercontent.com/assets/1126580/10114763/a985b44e-63ab-11e5-9c08-d0a0bc4d3d6b.png)

This is on OSX 10.11, with 
<img width="100" alt="screen shot 2015-09-25 at 5 34 50 pm" src="https://cloud.githubusercontent.com/assets/1126580/10114768/c0c38186-63ab-11e5-986d-7c4dff30e7c2.png">

**Comment by mnquintana** [comment] 2015-09-26 00:38
Does it work if you individually list each package? e.g. `apm uninstall nuclide-blame-provider-hg nuclide-debugger-atom` etc

**Comment by epmatsw** [comment] 2015-09-26 00:41
Yes. I tried `apm uninstall nuclide-blame-provider-hg nuclide-blame-ui` and now I've got 
<img width="292" alt="screen shot 2015-09-25 at 5 41 29 pm" src="https://cloud.githubusercontent.com/assets/1126580/10114814/b012506e-63ac-11e5-96a7-4cfc32f9b1ec.png">

**Comment by thomasjo** [comment] 2015-09-27 14:23
The problem is that you're using `apm list` and not stripping the textual tree decorators, i.e. `├──`. Simplest solution to that problem is to use apm's "bare" listing via `apm list -b`, thus your command becomes
```bash
apm list -b | grep nuclide | xargs apm uninstall
```

The underlying problem is masked since `apm uninstall` basically always returns successfully, even if there is no package installed matching the specified name. For instance `apm uninstall lolwut` returns a success. Additionally it seems as if the decorators in this case are masked from all but the first invocation to `apm uninstall` (clearly visible in your screenshot as `Uninstalling ├── ✓`)

I'm going to close this as this is primarily a user error, but I think we should open an issue for checking whether a package is installed before trying to uninstall (I haven't checked if such an issue already exists) /cc @atom/feedback 

---
NOTE: I'm not 100% sure apm supports version specification in conjunction with `apm uninstall`, and if it doesn't, you'll need to strip that as well via e.g. `cut`, `grep`, `awk`, or whatever.

**Closed by thomasjo** 2015-09-27 14:23 UTC
Labels: more-information-needed

**Comment by epmatsw** [comment] 2015-09-27 16:39
Ah, that makes sense then. Thanks for clarifying. I agree that it would be nice to have some indication that a non-existent package was uninstalled rather than "succeeding". Honestly I figured I was probably doing something dumb with this (my command-line fu is weak), but all the green checkmarks confused me.

**Comment by besser** [comment] 2015-11-17 03:44
Try this:
```
apm list -b | grep nuclide | cut -d'@' -f1 | xargs apm uninstall
```

**Comment by smleimberg** [comment] 2015-11-17 16:49
Thank you @besser. Your solution worked for me. Thanks. :)
