### ISSUE TITLE
apm enable/disable aren't implemented?

### ISSUE THREAD

**Issue by bronson** [atom/apm#389] opened 2015-07-02 23:35 UTC
I'd like to enable and disable packages from the command line.  (mostly, disabling 8 packages from the Settings View gets tedious quick).

Is there a reason apm doesn't support enabling and disabling packages?  If someone banged together a PR that implemented these commands, would it be likely to get merged?

**Comment by mnquintana** [comment] 2015-07-03 05:25
Thanks for the suggestion! This is a duplicate of https://github.com/atom/apm/issues/358 – please subscribe there for updates.

**Closed by mnquintana** 2015-07-03 05:25 UTC
