### ISSUE TITLE
Unable to publish or unpublish packages

### ISSUE THREAD

**Issue by Alhadis** [atom/apm#538] opened 2016-04-03 13:01 UTC
I [slapped together](https://github.com/Alhadis/oniguruma-comment) a really basic package to publish to Atom's repository, and was stopped at a bizarre error after running `apm publish oniguruma-comment` for the first time.

Basically, it told me it registered the package's name successfully, but was unable to _"prepare or tag a new release"_. Thing is, it didn't have to - the release was already tagged and pushed to the repo.

I tried entering the command by specifying the tag name specifically, but it resulted in the same errors. I sensed it might have something to do with the fact there were two releases tagged (one for the main files, and a follow-up patch release to correct some minor formatting errors in the readme).

So I wiped the repo, reinitialised the repository, and attempted to publish it again (this time with only one tagged release). [Then I find APM published a zombie package](https://atom.io/packages/oniguruma-comment) that I can't unpublish for... uh, God-knows-what-reason:

```
phoenix:oniguruma-comment johngardner$ apm publish --tag v1.0.0 oniguruma-comment
Preparing and tagging a new version ✗
npm ERR! npm version [<newversion> | major | minor | patch | premajor | preminor | prepatch | prerelease]
npm ERR! (run in package dir)
npm ERR! 'npm -v' or 'npm --version' to print npm version (2.13.3)
npm ERR! 'npm view <pkg> version' to view a package's published version
npm ERR! 'npm ls' to inspect current package/dependency versions
phoenix:oniguruma-comment johngardner$ apm unpublish !$
apm unpublish oniguruma-comment
Are you sure you want to unpublish oniguruma-comment? (yes) yes
Unpublishing oniguruma-comment ✗
Unpublishing failed: Unauthorized
phoenix:oniguruma-comment johngardner$ 
```

Here's the output of `apm -v`:

```
apm  1.6.0
npm  2.13.3
node 0.10.40
python 2.7.11
git 2.8.0
```

---

**EDIT:** Also, I don't know if this is relevant, but tonight I've started seeing warning messages from `git`:

```
Warning: Permanently added the RSA host key for IP address '192.30.252.120' to the list of known hosts.
```

It's displayed this twice now (each with different IPs, both belonging to GitHub: 192.30.252.120 and 192.30.252.122... is there something going on with the site's DNS?)

**Comment by jasonrudolph** [comment] 2017-04-05 20:02
> Then I find APM published a zombie package that I can't unpublish ...

@Alhadis: I think we've resolved this issue. 🤞

If you were the owner of the package's repository on github.com and you've deleted the repository, you should be able to use `apm unpublish` to successfully unpublish the package.

I think that was the root cause of the problems you ran into, so I'm gonna close this issue. If you still run into an issue trying to unpublish a package with a deleted repo, please let us know.

I see that your bug report also [describes some potential issues with the initial publishing process as well](https://github.com/atom/apm/issues/538#issue-145497760). If you're still able to reproduce that behavior, please let us know. :pray:

**Closed by jasonrudolph** 2017-04-05 20:02 UTC
